version: 2


aliases:
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

jobs:

  build_and_deploy_images_to_dockerhub:
    working_directory: ~/cyberd
    docker:
       - image: circleci/node:latest-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build Cyberd Image
          command: |
            cd cosmos/zeronet
            docker build -t build/cyberd ./
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag build/cyberd cybernode/cyberd:$CIRCLE_BRANCH
            docker push cybernode/cyberd:$CIRCLE_BRANCH

  update_changelog:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run:
          name: Build And Test Project
          command: |
            cid=$(docker run -d -it ferrarimarco/github-changelog-generator:1.14.3 -u cybercongress -p cyberd --exclude-tags-regex .*[.].*[.].*[.].* --token $CHANGELOG_GITHUB_TOKEN )
            docker attach $cid
            docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
            diff=$(git diff CHANGELOG.md)
            if [[  -n  "$diff" ]]; then
              git config --global user.email "cybercongress42@gmail.com"
              git config --global user.name "Cyber Admin"
              git add CHANGELOG.md
              git commit -m "Circle CI: Update Changelog"
              git push --set-upstream origin master
            fi


  update_docs:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Clone congress repo
        working_directory: ~/workdir
        command: |
          git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git
    - deploy:
        name: Update docs from cyber search repo
        working_directory: ~/workdir/congress
        command: |
          # We need to remove current files in folder to avoid duplicating renamed files
          rm -rf ./knowledge/docs/cyberd/*
          cp -r ~/build/docs/. ./knowledge/docs/cyberd/
          cp ~/build/CHANGELOG.md ./knowledge/docs/cyberd/Release_notes.md
          cp ~/build/CONTRIBUTING.md ./knowledge/docs/cyberd/Contributing.md
          cp ~/build/ROADMAP.md ./knowledge/docs/cyberd/Roadmap.md
          git add -N knowledge/docs/cyberd
          diff=$(git diff knowledge/docs/cyberd/)
          if [[  -n  "$diff" ]]; then
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add knowledge/docs/cyberd/
            git commit -m "Circle CI: Update Docs"
            # Push quietly to prevent showing the token in log
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git master
          fi

workflows:
  version: 2
  search_build:
    jobs:
      - update_changelog:
          filters:
            branches:
              only: master
      - update_docs:
          filters:
            branches:
              only: master
