version: 2

jobs:

  build_and_deploy_images_to_dockerhub:
    working_directory: ~/cyberd
    docker:
       - image: circleci/node:latest-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build Cyberd Image
          command: |
            cd cosmos/poc
            docker build -t build/cyberd ./
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag build/cyberd cybernode/cyberd:$CIRCLE_BRANCH
            docker push cybernode/cyberd:$CIRCLE_BRANCH

  restart_gcloud_seed_cluster-job:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
        name: Restart Cyberd Seed Cluster
        command: |
          echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${CIRCLE_WORKING_DIRECTORY}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}


workflows:
  version: 2
  search_build:
    jobs:
      - build_and_deploy_images_to_dockerhub
